# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5fd3f2b84828a25c4b5b2fef4a1b02de129db9ae270a241034c4c2a90bc004edbe4ef4440190c166424eb3729cd0f8a1814d4ec1159221afd5b3a690d8d07fa

test:
  secret_key_base: 062f7f127aac38eaad973bc4cd75a319cc29a527ba753a75cfbf0a6e90c79fc25f31c2f8374a16bbac7ccb6389a70fad622e275dd95746bdc26bb552cb2d42ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
